version: '3'

services:
  webhook:
    image: 'esgimicroci/al2-webhook:latest'
    container_name: 'micro-ci-webhook'
    restart: always
    ports:
      - "${WEBHOOK_PORT:-9000}:3000"
    environment:
      - BROKER_IP=${BROKER_IP:-10.0.0.5:40701}
    networks:
      - micro-ci:

networks:
  micro-ci:
    driver: bridge
