version: '3'

services:
  webhook:
    image: 'esgimicroci/al2-webhook:latest'
    container_name: 'micro-ci-webhook'
    restart: always
    ports:
      - "${WEBHOOK_PORT:-9000}:3000"
    environment:
      - BROKER_IP=${BROKER_IP:-10.0.0.5:40701}
      - BROKER_USER=${BROKER_USER:-root}
      - BROKER_PASSWORD=${BROKER_PASSWORD:-root}
      - CONSUL_HOST=${CONSUL_HOST:-10.0.0.5}
      - CONSUL_PORT=${CONSUL_PORT:-40601}
      - CONSUL_TOKEN=${CONSUL_TOKEN:-azertyuiop}
      - WEBHOOK_PORT=${WEBHOOK_PORT:-9000}
    networks:
      - micro-ci

networks:
  micro-ci:
    driver: bridge
